public enum Fach {
	RELIGION_RK,
	RELIGION_EV,
	ETHIK,
	DEUTSCH,
	SOZIALKUNDE,
	ENGLISCH,
	BETRIEBSWIRTSCHAFTLICHE_PROZESSE,
	RECHNUNGSWESEN_UND_CONTROLLING,
	VERSORGUNGSNETZE,
	IT_SYSTEME,
	VERNETZE_SYSTEME,
	ANWENDUNGSENTWICKLUNG_UND_PROGRAMMIERUNG
}