

public enum Schulabschluss {
	MITTELSCHULABSCHLUSS,
	MITTELSCHULABSCHLUSS_QUALIFIZIEREND,
	MITTLERER_SCHULABSCHLUSS,
	FACHHOCHSCHULREIFE_FACHGEBUNDEN,
	FACHHOCHSCHULREIFE_ALLGEMEIN,
	HOCHSCHULREIFE_FACHGEBUNDEN,
	HOCHSCHULREIFE_ALLGEMEIN
}